# Generated by Django 3.0.5 on 2021-04-02 13:08

from django.db import migrations, models
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('securepassw', models.CharField(max_length=500)),
                ('like_tags', djongo.models.fields.ArrayField(blank=True, model_container=home.models.Tag, null=True)),
                ('dislike_tags', djongo.models.fields.ArrayField(blank=True, model_container=home.models.Tag, null=True)),
            ],
        ),
    ]
