# Generated by Django 3.0.5 on 2021-05-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210503_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
