# Generated by Django 3.0.5 on 2021-05-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210513_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replys',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dislike_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_tags',
        ),
        migrations.DeleteModel(
            name='Dislike_Tags',
        ),
        migrations.DeleteModel(
            name='Like_Tags',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
