# Generated by Django 3.0.5 on 2021-04-23 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210422_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likers_comment',
            field=models.ManyToManyField(related_name='likers_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
