# Generated by Django 3.0.5 on 2021-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='home/static/home/images/profile_pics/<django.db.models.fields.CharField>/', verbose_name='Image'),
        ),
    ]
